# Generated by Django 6.0.7 on 2026-07-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('date_label', models.CharField(help_text='Texte libre affiché tel quel, ex: Juillet 2026', max_length=50, verbose_name='Date affichée')),
                ('body', models.TextField(verbose_name='Texte')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actus/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('initials', models.CharField(blank=True, help_text='Ex: CB. Laissez vide pour les déduire automatiquement du nom.', max_length=4, verbose_name='Initiales (avatar)')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle')),
                ('mission', models.TextField(verbose_name='Mission / description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe',
                'ordering': ['order', 'name'],
            },
        ),
    ]
