# Generated by Django 6.0.7 on 2026-07-28 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identifiant anonyme stocké dans un cookie, stable entre les visites.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(help_text='Page visitée, ex: /en/projets.html', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('lang', models.CharField(blank=True, default='', help_text="fr / en / ar déduit de l'URL", max_length=10)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('device_type', models.CharField(choices=[('desktop', 'Ordinateur'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('bot', 'Robot'), ('other', 'Autre')], default='other', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_new_visitor', models.BooleanField(default=False, help_text='Première visite jamais enregistrée pour ce visitor_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='tracking_vi_created_5d664e_idx'), models.Index(fields=['visitor_id'], name='tracking_vi_visitor_68821b_idx')],
            },
        ),
    ]
